apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-demo-checkoutservice
  labels:
    app.kubernetes.io/name: opentelemetry-demo-checkoutservice
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/component: checkoutservice
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/part-of: opentelemetry-demo
    opentelemetry.io/name: opentelemetry-demo-checkoutservice
spec:
  type: ClusterIP
  ports:
    - name: tcp-service
      port: 8080
      targetPort: 8080
  selector:
    opentelemetry.io/name: opentelemetry-demo-checkoutservice